### ISSUE TITLE
Logstash 1.5 complains about undefinied "to_json" method

### ISSUE THREAD

**Issue by gruzewski** [logstash-plugins/logstash-output-datadog#2]
Hi,

I had an issue with undefined "to_json" method in datadog.rb, with the line below:

```
request.body = dd_event.to_json
```

I have workaround it by adding 

```
require "json"
```

My setup: Logstash 1.5, Ubuntu 14.04

Really good stuff! And all my colleagues were impressed ;)

**Comment by guyboertje** [comment]
Current release does not use `dd_event.to_json`. Closing
